-- Migration: create cars catalog table
-- SQLite dialect

CREATE TABLE IF NOT EXISTS cars (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

-- Populate with iRacing cars
INSERT OR IGNORE INTO cars (name) VALUES
    ('Acura ARX-06 GTP'),
    ('Acura NSX GT3 EVO 22'),
    ('ARCA Chevrolet SS'),
    ('ARCA Ford Mustang'),
    ('ARCA Toyota Camry'),
    ('Aston Martin DBR9 GT1'),
    ('Aston Martin Vantage GT3 EVO'),
    ('Aston Martin Vantage GT4'),
    ('Audi 90 GTO'),
    ('Audi R18'),
    ('Audi R8 LMS EVO II GT3'),
    ('Audi RS 3 LMS TCR'),
    ('BMW M Hybrid V8'),
    ('BMW M2 CS Racing'),
    ('BMW M4 F82 GT4 - 2018'),
    ('BMW M4 G82 GT4 Evo'),
    ('BMW M4 GT3 EVO'),
    ('BMW M8 GTE'),
    ('Cadillac CTS-V Racecar'),
    ('Cadillac V-Series.R GTP'),
    ('Chevrolet Corvette C6.R GT1'),
    ('Chevrolet Corvette C7 Daytona Prototype'),
    ('Chevrolet Corvette C8.R GTE'),
    ('Chevrolet Corvette Z06 GT3.R'),
    ('Dallara F3'),
    ('Dallara IL-15'),
    ('Dallara iR-01'),
    ('Dallara IR18'),
    ('Dallara P217'),
    ('Dirt Big Block Modified'),
    ('Dirt Late Model - Limited'),
    ('Dirt Micro Sprint Car - Winged'),
    ('Dirt Midget'),
    ('Dirt Mini Stock'),
    ('Dirt Sprint Car - 305'),
    ('Dirt Sprint Car - 360 Non-Winged'),
    ('Dirt Street Stock'),
    ('Dirt UMP Modified'),
    ('Ferrari 296 Challenge'),
    ('Ferrari 296 GT3'),
    ('Ferrari 488 GT3 Evo 2020'),
    ('Ferrari 488 GTE'),
    ('Ferrari 499P'),
    ('FIA Cross Car'),
    ('FIA F4'),
    ('Ford Fiesta RS WRC'),
    ('Ford GT GT2'),
    ('Ford GTE'),
    ('Ford Mustang FR500S'),
    ('Ford Mustang GT3'),
    ('Ford Mustang GT4'),
    ('Formula Renault 2.0'),
    ('Formula Renault 3.5'),
    ('Formula Vee'),
    ('Gen 4 Chevrolet Monte Carlo - 2003'),
    ('Gen 4 Ford Taurus - 2003'),
    ('Global Mazda MX-5 Cup'),
    ('Honda Civic Type R TCR'),
    ('HPD ARX-01c'),
    ('Hyundai Elantra N TCR'),
    ('Hyundai Veloster N TCR'),
    ('Indy Pro 2000 PM-18'),
    ('Kia Optima'),
    ('Lamborghini Huracán GT3 EVO'),
    ('Late Model Stock'),
    ('Legends Ford ''34 Coupe'),
    ('Ligier JS P320'),
    ('Lotus 49'),
    ('Lotus 79'),
    ('Lucas Oil Off Road Pro 2 Lite'),
    ('Lucas Oil Off Road Pro 2 Truck'),
    ('McLaren 570S GT4'),
    ('McLaren 720S GT3 EVO'),
    ('McLaren MP4-30'),
    ('Mercedes-AMG GT3 2020'),
    ('Mercedes-AMG GT4'),
    ('Mercedes-AMG W12 E Performance'),
    ('Mercedes-AMG W13 E Performance'),
    ('Mini Stock'),
    ('Modified - SK'),
    ('NASCAR Cup Series Chevrolet Camaro ZL1'),
    ('NASCAR Cup Series Ford Mustang'),
    ('NASCAR Cup Series Next Gen Chevrolet Camaro ZL1'),
    ('NASCAR Cup Series Next Gen Ford Mustang'),
    ('NASCAR Cup Series Next Gen Toyota Camry'),
    ('NASCAR Cup Series Toyota Camry'),
    ('NASCAR Legends Buick LeSabre - 1987'),
    ('NASCAR Legends Chevrolet Monte Carlo - 1987'),
    ('NASCAR Legends Ford Thunderbird - 1987'),
    ('NASCAR Legends Pontiac Grand Prix - 1987'),
    ('NASCAR Truck Chevrolet Silverado'),
    ('NASCAR Truck Ford F150'),
    ('NASCAR Truck Toyota Tundra TRD Pro'),
    ('NASCAR XFINITY Chevrolet Camaro'),
    ('NASCAR XFINITY Ford Mustang'),
    ('NASCAR XFINITY Toyota Supra'),
    ('Nissan GTP ZX-T'),
    ('Pontiac Solstice'),
    ('Porsche 718 Cayman GT4 Clubsport MR'),
    ('Porsche 911 Cup (992.2)'),
    ('Porsche 911 GT3 R (992)'),
    ('Porsche 911 RSR'),
    ('Porsche 919'),
    ('Porsche 963 GTP'),
    ('Porsche Mission R'),
    ('Radical SR10'),
    ('Radical SR8'),
    ('Ray FF1600'),
    ('Renault Clio'),
    ('Ruf RT 12R AWD'),
    ('SCCA Spec Racer Ford'),
    ('Silver Crown'),
    ('Skip Barber Formula 2000'),
    ('Sprint Car'),
    ('SRX'),
    ('Stock Car Brasil Chevrolet Cruze'),
    ('Stock Car Brasil Toyota Corolla'),
    ('Street Stock - Casino M2'),
    ('Street Stock - Panther C1'),
    ('Subaru WRX STI'),
    ('Super Formula Lights'),
    ('Super Formula SF23 - Toyota'),
    ('Super Late Model'),
    ('Supercars Chevrolet Camaro Gen 3'),
    ('Supercars Ford Mustang Gen 3'),
    ('Toyota GR86'),
    ('USF 2000'),
    ('VW Beetle'),
    ('VW Jetta TDI Cup'),
    ('Williams-Toyota FW31'),
    ('[Legacy] ARCA Menards Chevrolet Impala'),
    ('[Legacy] Audi R8 LMS GT3'),
    ('[Legacy] BMW Z4 GT3'),
    ('[Legacy] Dallara DW12'),
    ('[Legacy] Dallara IR-05'),
    ('[Legacy] Ferrari 488 GT3'),
    ('[Legacy] Mazda MX-5 Cup - 2010'),
    ('[Legacy] McLaren MP4-12C GT3'),
    ('[Legacy] Mercedes-AMG GT3'),
    ('[Legacy] NASCAR Cup Chevrolet Impala COT - 2009'),
    ('[Legacy] NASCAR Cup Chevrolet SS - 2013'),
    ('[Legacy] NASCAR Cup Ford Fusion - 2016'),
    ('[Legacy] NASCAR Nationwide Chevrolet Impala - 2012'),
    ('[Legacy] NASCAR Truck Chevrolet Silverado - 2008'),
    ('[Legacy] NASCAR Xfinity Chevrolet Camaro - 2014'),
    ('[Legacy] NASCAR Xfinity Ford Mustang - 2016'),
    ('[Legacy] NASCAR Xfinity Toyota Camry - 2015'),
    ('[Legacy] Porsche 911 GT3 Cup (991)'),
    ('[Legacy] Porsche 911 GT3 Cup (992.1)'),
    ('[Legacy] Porsche 911 GT3 R'),
    ('[Legacy] Pro Mazda'),
    ('[Legacy] Riley MkXX Daytona Prototype - 2008'),
    ('[Legacy] Supercars Ford Mustang GT'),
    ('[Legacy] Supercars Holden ZB Commodore'),
    ('[Legacy] V8 Supercar Ford Falcon - 2009'),
    ('[Legacy] V8 Supercar Ford FG Falcon - 2014'),
    ('[Legacy] V8 Supercar Holden VF Commodore - 2014'),
    ('[Retired] Chevrolet Monte Carlo SS');
