-- Migration: create tracks catalog table
-- SQLite dialect

CREATE TABLE IF NOT EXISTS tracks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

-- Populate with iRacing tracks
INSERT OR IGNORE INTO tracks (name) VALUES
    ('Adelaide Street Circuit'),
    ('Algarve International Circuit'),
    ('Auto Club Speedway'),
    ('Autódromo Hermanos Rodríguez'),
    ('Autodromo Internazionale del Mugello'),
    ('Autodromo Internazionale Enzo e Dino Ferrari'),
    ('Autódromo José Carlos Pace'),
    ('Autodromo Nazionale Monza'),
    ('Barber Motorsports Park'),
    ('Bark River International Raceway'),
    ('Brands Hatch Circuit'),
    ('Bristol Motor Speedway'),
    ('Cadwell Park Circuit'),
    ('Canadian Tire Motorsports Park'),
    ('Cedar Lake Speedway'),
    ('Centripetal Circuit'),
    ('Charlotte Motor Speedway'),
    ('Chicago Street Course'),
    ('Chicagoland Speedway'),
    ('Chili Bowl'),
    ('Circuit de Barcelona Catalunya'),
    ('Circuit de Lédenon'),
    ('Circuit de Nevers Magny-Cours'),
    ('Circuit de Spa-Francorchamps'),
    ('Circuit des 24 Heures du Mans'),
    ('Circuit Gilles Villeneuve'),
    ('Circuit of the Americas'),
    ('Circuit Zandvoort'),
    ('Circuit Zolder'),
    ('Circuito de Jerez - Ángel Nieto'),
    ('Circuito de Navarra'),
    ('Concord Speedway'),
    ('Crandon International Raceway'),
    ('Darlington Raceway'),
    ('Daytona International Speedway'),
    ('Daytona Rallycross and Dirt Road'),
    ('Detroit Grand Prix at Belle Isle'),
    ('Donington Park Racing Circuit'),
    ('Dover Motor Speedway'),
    ('EchoPark Speedway (Atlanta)'),
    ('Eldora Speedway'),
    ('Fairbury Speedway'),
    ('Federated Auto Parts Raceway at I-55'),
    ('Firebird Motorsports Park'),
    ('Five Flags Speedway'),
    ('Fuji International Speedway'),
    ('Hickory Motor Speedway'),
    ('Hockenheimring Baden-Württemberg'),
    ('Homestead Miami Speedway'),
    ('Hungaroring'),
    ('Huset''s Speedway'),
    ('Indianapolis Motor Speedway'),
    ('Iowa Speedway'),
    ('iRacing Superspeedway'),
    ('Irwindale Speedway'),
    ('Kansas Speedway'),
    ('Kentucky Speedway'),
    ('Kevin Harvick''s Kern Raceway'),
    ('Knockhill Racing Circuit'),
    ('Knoxville Raceway'),
    ('Kokomo Speedway'),
    ('LA Coliseum Raceway'),
    ('Langley Speedway'),
    ('Lanier National Speedway'),
    ('Lånkebanen (Hell RX)'),
    ('Las Vegas Motor Speedway'),
    ('Lernerville Speedway'),
    ('Limaland Motorsports Park'),
    ('Lime Rock Park'),
    ('Lincoln Speedway'),
    ('Long Beach Street Circuit'),
    ('Lucas Oil Indianapolis Raceway Park'),
    ('Lucas Oil Speedway'),
    ('Martinsville Speedway'),
    ('Miami International Autodrome'),
    ('Michigan International Speedway'),
    ('Mid-Ohio Sports Car Course'),
    ('Millbridge Speedway'),
    ('Misano World Circuit Marco Simoncelli'),
    ('Mobility Resort Motegi'),
    ('MotorLand Aragón'),
    ('Motorsport Arena Oschersleben'),
    ('Mount Panorama Circuit'),
    ('Mount Washington Hillclimb'),
    ('Myrtle Beach Speedway'),
    ('Nashville Fairgrounds Speedway'),
    ('Nashville Superspeedway'),
    ('New Hampshire Motor Speedway'),
    ('New Jersey Motorsports Park'),
    ('New Smyrna Speedway'),
    ('North Wilkesboro Speedway'),
    ('Nürburgring Combined'),
    ('Nürburgring Grand-Prix-Strecke'),
    ('Nürburgring Nordschleife'),
    ('Okayama International Circuit'),
    ('Oran Park Raceway'),
    ('Oswego Speedway'),
    ('Oulton Park Circuit'),
    ('Oxford Plains Speedway'),
    ('Phillip Island Circuit'),
    ('Phoenix Raceway'),
    ('Pocono Raceway'),
    ('Port Royal Speedway'),
    ('Portland International Raceway'),
    ('Red Bull Ring'),
    ('Richmond Raceway'),
    ('Road America'),
    ('Road Atlanta'),
    ('Rockingham Speedway'),
    ('Rudskogen Motorsenter'),
    ('Sachsenring'),
    ('Sandown International Motor Raceway'),
    ('Sebring International Raceway'),
    ('Shell V-Power Motorsport Park at The Bend'),
    ('Silverstone Circuit'),
    ('Slinger Speedway'),
    ('Snetterton Circuit'),
    ('Sonoma Raceway'),
    ('South Boston Speedway'),
    ('Southern National Motorsports Park'),
    ('Stafford Motor Speedway'),
    ('Summit Point Raceway'),
    ('Suzuka International Racing Course'),
    ('Talladega Superspeedway'),
    ('Texas Motor Speedway'),
    ('The Bullring'),
    ('The Dirt Track at Charlotte'),
    ('The Milwaukee Mile'),
    ('Thompson Speedway Motorsports Park'),
    ('Thruxton Circuit'),
    ('Tsukuba Circuit'),
    ('USA International Speedway'),
    ('Volusia Speedway Park'),
    ('Watkins Glen International'),
    ('WeatherTech Raceway at Laguna Seca'),
    ('Weedsport Speedway'),
    ('Wild West Motorsports Park'),
    ('Williams Grove Speedway'),
    ('Willow Springs International Raceway'),
    ('Winton Motor Raceway'),
    ('World Wide Technology Raceway (Gateway)'),
    ('[Legacy] Kentucky Speedway - 2011'),
    ('[Legacy] Michigan International Speedway - 2009'),
    ('[Legacy] Phoenix Raceway - 2008'),
    ('[Legacy] Pocono Raceway - 2009'),
    ('[Legacy] Silverstone Circuit - 2008'),
    ('[Legacy] Texas Motor Speedway - 2009'),
    ('[Retired] Charlotte Motor Speedway'),
    ('[Retired] Lime Rock Park - 2008'),
    ('[Retired] Phoenix Raceway'),
    ('[Retired] Virginia International Raceway');
